name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - master  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Setup Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
        
    - name: Build the application with Maven
      run: mvn clean package -DskipTests

    - name: Upload target directory
      uses: actions/upload-artifact@v4
      with:
        name: target-artifact
        path: target/

  test:
    name: Automated Testing
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Tests
        run: mvn test

  deploy:
    name: Deploy to OpenShift
    needs: test
    runs-on: ubuntu-latest

    steps:

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: target-artifact
        path: target/

    - name: OpenShift Client Installer
      uses: redhat-actions/oc-installer@v1.2
          
    - name: Log in to OpenShift
      env:
        OPENSHIFT_API_URL: ${{ secrets.OPENSHIFT_API_URL }}
        OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      run: |
        oc login $OPENSHIFT_API_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true
    - name: Set project to agile-2025-labs
      run: |
        oc project agile-2025-labs
    - name: Build and deploy the app to OpenShift
      run: |
        # OpenShift setup uses Source-to-Image (S2I) 
        oc start-build health-tracker-rest-openshift-labs --from-dir=target/ --follow
    
    - name: Check deployment status
      run: |
        oc rollout status deployment/health-tracker-rest-openshift-labs
